modLoader = "javafml"
loaderVersion = "[38,)"
license = "Unlicense"

[[mods]]
modId = "xlpackets-renewed"
version = "${version}"
displayName = "XL Packets Renewed"
description = "Mod to help clients connect to servers with large datapacks"

displayURL = "https://www.curseforge.com/minecraft/mc-mods/xl-packets-renewed"
authors = "Tfarecnim, TheQuantumXenon"
logoFile = "icon.png"