modLoader = "javafml" #mandatory
loaderVersion = "[38,)" #mandatory
license = "Unlicense" #mandatory

[[mods]]
modId = "xlpackets" #mandatory
version = "${version}" #mandatory
displayName = "XL Packets" #mandatory
authors = "Tfarecnim" #optional
description = "Mod to help clients connect to servers with large datapacks" #mandatory