modLoader = "javafml"
loaderVersion = "[38,)"
license = "Unlicense"

[[mods]]
modId = "xlpackets-renewed"
version = "${version}"
displayName = "XL Packets Renewed"
authors = "Tfarecnim, TheQuantumXenon"
description = "Mod to help clients connect to servers with large datapacks"